### ISSUE TITLE
Domain Name Change

### ISSUE THREAD

**Issue by chrispalasz** [achow101/btcinformation.org#12]
Hi, my name is Chris and I’m a co-organizer of the Seoul Bitcoin meetup in Korea. I like this project and hope to see it succeed. For my first contribution, I’d like to suggest the following improvement.

Issue: We should change the domain name for this project.

Pros:

P-1) Improve accuracy/ambiguity
- It would be better to have ‘bitcoin’ in the name to be more accurate and clear what the website represents

P-2) Improve ease of sharing
- a more catchy name will help people remember it and help it to stick when people hear or see the name

P-3) Improve community participation and project traction
- a better name (like it or not) improves perceived credibility of the project which in turn improves community participation and sharing.

Cons:

C-1) Project already launched

C-1 solution: The current domain could redirect to the new domain until a certain period of time has passed.

C-2) Domain name availability is a barrier

C-2 solution: I have compiled a list of 7 available domain names which I think are improved alternatives to the current domain for the project. I do not own them all so the list will remain private until there is consensus that a better domain name would benefit the project and that we are willing to make a change.

C-3) Domain name costs

C-3 solution: I’m willing to help donate to the cost of acquiring a new domain.

Final Comments:

To be clear, my support for this project should not be seen as an attack on bitcoin.org - which is also a very good resource. I just recognize that this project will be community run and consensus driven.

And the more great resources that Bitcoin has available for public access, especially neutral ones - the better.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by harding** [comment]
I think a shorter and easier-to-remember domain name would also be useful even now that the site has launched, and I'm also willing to donate a modest amount of money towards acquiring a reasonable name.

**Comment by jnewbery** [comment]
> I'm also willing to donate a modest amount of money towards acquiring a reasonable name.

I'll also throw in a few nBTC.

**Comment by achow101** [comment]
It would be nice to have a better domain name. The current name can certainly be redirected to a new domain.

If there are domains that you would like, perhaps these can be registered and then a vote done to see which ones people like those most?

I am certainly willing to donate some money towards domain registration, after all, I registered the one that we are currently using.

**Comment by chrispalasz** [comment]
Okay. I’ve been busy the past few days, but I do have a list of alternatives. I am planning on getting feedback about that list and organizing a buy up of the top choices. Once the domains are owned by people willing to donate their ownership to the project, I’ll post again and see if we can agree on one of those. 

If not, that’s okay. I think some of them are good enough so that the owners who want a bitcoin domain will not be upset being stuck with ownership.

I plan to post those sometime in Aug 16-19.

If you would like to participate in the buy-up, please contact me privately and I can share the list and you can see if you’d be willing to buy any of them.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by achow101** [comment]
This project is no longer being maintained.
