### ISSUE TITLE
Improve list of linked exchanges

### ISSUE THREAD

**Issue by scottlledeuce** [achow101/btcinformation.org#13]
As it stands there seems to be inaccurate information relating to both popular international exchanges and exchanges by country. 

For example, LUNO is not a Nigerian or South African exchange but rather based in London, Sure they have customers there but its a misrepresentation and could come off as an endorsement of their services in the country and therefore is not impartial.

I would also favor splitting the international exchanges section into centralized and non-centralized exchanges. also, there seems to be no consistency in terms of criteria for listing an exchange, 
In terms of p2p exchanges I see you listed local bitcoins which have most volume and bisq which has basically zero volume but some some reason did not include paxful which is far bigger and more flexible than Bisq

**Comment by achow101** [comment]
This project is no longer being maintained.
