### ISSUE TITLE
Update rpc docs to 0.18.0

### ISSUE THREAD

**Issue by maflcko** [achow101/btcinformation.org#27]
Can be done by cherry-picking https://github.com/bitcoin-dot-org/bitcoin.org/pull/2980

**Comment by harding** [comment]
~~MarcoFalke 0.18.0 are already on the site: https://bitcoincore.org/en/doc/0.18.0/~~

~~BitcoinCore.org doesn't use the same RPC docs as Bitcoin.org, so we couldn't cherry pick from them anyway.~~

Gah, I was thinking this was a different repository.  Please ignore.  Sorry.

**Comment by achow101** [comment]
This project is no longer being maintained.
