### ISSUE TITLE
[Feature request]: Link to repo from website + FAQ section re this fork

### ISSUE THREAD

**Issue by infominer33** [achow101/btcinformation.org#28]
it would be nice if there was a little github icon somewhere on the site.. maybe there is a link somewhere, I didn't find it.

also some small section in the FAQ about this fork, and why someone would visit here rather than bitcoin.org.

I know there was a twitter thread, maybe a blogpost idk.. not sure where to find that.

**Comment by infominer33** [comment]
I did find an about page via search, and looking for a link to it on the homepage, I found a link to the blog real tiny at the bottom :D

https://btcinformation.org/en/posts/announcing-btcinformation

this post is great and exactly what I needed for the moment. 

Thank you!

**Comment by achow101** [comment]
This project is no longer being maintained.
