### ISSUE TITLE
[Bug] "Install" button on choose a wallet, Arcbit, page is broken

### ISSUE THREAD

**Issue by infominer33** [achow101/btcinformation.org#29]
https://btcinformation.org/en/wallets/desktop/windows/arcbit/
https://btcinformation.org/en/wallets/desktop/mac/arcbit/
https://btcinformation.org/en/wallets/desktop/linux/arcbit/

each has this broken link to the chrome web-store

https://chrome.google.com/webstore/detail/arcbit-bitcoin-wallet/dkceiphcnbfahjbomhpdgjmphnpgogfk

**Comment by infominer33** [comment]
ahh yes... even their website is down `Latest commit fe0e9d0 on Jan 1, 2018`

https://github.com/arcbit/arcbit-web

**Comment by infominer33** [comment]
I would just go ahead and remove https://github.com/achow101/btcinformation.org/blob/master/_wallets/arcbit.md then submit a pull-request after I've gone through the rest of them...

However, I'm guessing there could be places those are referenced elsewhere, and am just getting to know the lay of the land.

I'm learning jekyll, but this is a little beyond my understanding, as I've been using themes

**Comment by achow101** [comment]
This project is no longer being maintained.
