### ISSUE TITLE
doc: generatetoaddress should not require wallet support

### ISSUE THREAD

**Issue by glowang** [achow101/btcinformation.org#35]
Currently, the generatetoaddress documentation says that wallet support is required.

This seems to contradict the current implementation. We have a wallet_disable functional test in bitcoin core that confirms that it is possible to generatetoaddress with `-disablewallet`: 

```
# Checking mining to an address without a wallet. Generating to a valid address should succeed
# but generating to an invalid address will fail.
self.nodes[0].generatetoaddress(1, 'mneYUmWYsuk7kySiURxCi3AGxrAqZxLgPZ')
assert_raises_rpc_error(-5, "Invalid address", self.nodes[0].generatetoaddress, 1, '3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy')
```

**Comment by jnewbery** [comment]
RPC help text is now generated manually at https://bitcoincore.org/en/doc/, so perhaps the entire RPC section on btcinformation.org should be removed?

**Comment by glowang** [comment]
I should have been more clear about where I see this: https://btcinformation.org/en/developer-reference#generatetoaddress 

However, the doc on https://bitcoincore.org/en/doc/0.20.0/rpc/generating/generatetoaddress/  does not mention wallet support as a requirement.

**Comment by achow101** [comment]
This project is no longer being maintained.
