### ISSUE TITLE
Hamburger menu doesn't work

### ISSUE THREAD

**Issue by harding** [achow101/btcinformation.org#5]
Steps to reproduce:

1. In Mozilla Firefox (but [reported on mobile in general](https://twitter.com/hazwire/status/1025839819778416640))
2. Enter responsive design mode (Ctrl-Shift-M), screen looks like this:

![2018-08-04-16_32_23_144558246](https://user-images.githubusercontent.com/61096/43680254-02247ef2-9804-11e8-8580-dc486609f8bb.png)

3. Click the hamburger menu in the top-right corner

Expected result: a menu appears

Observed result: nothing happens onscreen, but I get the following error in the JS console:

```text
TypeError: ml is null[Learn More]  base.js:149:5
	mobileMenuShow/show https://btcinformation.org/js/base.js:149:5
	onTouchClick https://btcinformation.org/js/base.js:139:7
	mobileMenuShow https://btcinformation.org/js/base.js:153:3
	onclick https://btcinformation.org/en/posts/announcing-btcinformation:1:1
```

I'm guessing maybe we removed a bit too much JS in the purge.

**Comment by TheRec** [comment]
It is related to to the current broken/missing multi-language support and as a result the missing selection mechanism for language. I suppose the priority should rather be to fix the multi-language aspect of the website first, it should fix this issue too.
