### ISSUE TITLE
Other languages than English are unavailable

### ISSUE THREAD

**Issue by TheRec** [achow101/btcinformation.org#6]
The language selection menu in the footer is missing.

Accessing other languages directly though URL (for example https://btcinformation.org/fr/) causes an infinite redirection loop after an HTTP 404 Error.

**Comment by achow101** [comment]
I'm working on setting up a transifex organization and project so that we can re-enable translations.

**Comment by achow101** [comment]
The transifex organization and project are now live. The links in the documentation should be correct. It is https://www.transifex.com/btcinformationorg/btcinformationorg

**Comment by harding** [comment]
Translations are a huge maintenance burden.  I'd really prefer they remain off until everything else is worked out and we decide if we want to make any content changes.

**Comment by harding** [comment]
Note: the infinite loop only occurs if your browser's preferred language is set to something besides English.  I have a patch incoming to fix it.  (Thanks @TheRec for reporting!)

**Comment by achow101** [comment]
This project is no longer being maintained.
